server:
  port: 5555

spring:
  application:
    name: webdocs
  thymeleaf:
    cache: false
  session:
    store-type: none

webdocs:
  mynger-api-url: http://api.mynger.com
  deepdiary-api-url: http://api.deepdiary.mynger.com
  output-dir: ${java.io.tmpdir}/webdocs-output

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
